package dhcpv6

import (
	"crypto/sha256"
	"errors"
	"fmt"
	"log/slog"
	"math/big"
	"net/netip"
	"strings"
	"sync"

	"modern-dhcp/internal/netutil"
)

var (
	linkLocal10Prefix = netip.MustParsePrefix("fe80::/10")
	linkLocal64Prefix = netip.MustParsePrefix("fe80::/64")
	slaacHashCache    sync.Map
	slaacBigIntPool   = sync.Pool{New: func() any { return new(big.Int) }}
)

// borrowBigInt borrows a reusable big.Int from the pool.
//
// Parameters:
//   - none
//
// Returns:
//   - *big.Int: a zeroed big.Int ready for arithmetic operations.
//
// Applicable scenario:
//   - Used in hot SLAAC derivation paths to reduce temporary allocations.
func borrowBigInt() *big.Int {
	v := slaacBigIntPool.Get()
	if v == nil {
		return new(big.Int)
	}
	b, ok := v.(*big.Int)
	if !ok {
		slog.Warn("dhcpv6 slaac pool type mismatch", slog.String("error", "pool item is not *big.Int"))
		return new(big.Int)
	}
	b.SetInt64(0)
	return b
}

// releaseBigInt resets and returns a big.Int to the pool.
//
// Parameters:
//   - v: pooled big.Int instance to be released.
//
// Returns:
//   - none
//
// Applicable scenario:
//   - Called with defer in SLAAC math paths to reduce GC pressure.
func releaseBigInt(v *big.Int) {
	if v == nil {
		return
	}
	v.SetInt64(0)
	slaacBigIntPool.Put(v)
}

// seedHash returns the SHA256 digest for a seed with cache reuse.
//
// Parameters:
//   - seed: deterministic SLAAC seed string.
//
// Returns:
//   - [sha256.Size]byte: SHA256 digest bytes for the seed.
//
// Applicable scenario:
//   - Used when deriving addresses repeatedly for identical client identity seeds.
func seedHash(seed string) [sha256.Size]byte {
	if cached, ok := slaacHashCache.Load(seed); ok {
		if sum, typeOK := cached.([sha256.Size]byte); typeOK {
			return sum
		}
		slog.Warn("dhcpv6 slaac hash cache type mismatch", slog.Int("seed_len", len(seed)))
	}
	sum := sha256.Sum256([]byte(seed))
	actual, _ := slaacHashCache.LoadOrStore(seed, sum)
	if final, ok := actual.([sha256.Size]byte); ok {
		return final
	}
	return sum
}

// buildSLAACSeed constructs deterministic identity material for SLAAC derivation.
//
// Parameters:
//   - pkt: DHCPv6 request packet carrying client identifiers (DUID, MAC, relay info, IAID).
//
// Returns:
//   - string: canonical seed payload joined by '|'.
//   - error: non-nil when no usable identity fragment exists.
//
// Applicable scenario:
//   - Called before SLAAC address derivation in hybrid DHCPv6 + SLAAC flows.
func buildSLAACSeed(pkt Packet) (string, error) {
	var parts []string
	if pkt.DUID != "" {
		parts = append(parts, pkt.DUID)
	}
	if pkt.ClientMAC != nil {
		parts = append(parts, pkt.ClientMAC.String())
	}
	if pkt.LinkAddr != nil {
		parts = append(parts, pkt.LinkAddr.String())
	}
	if pkt.PeerAddr != nil {
		parts = append(parts, pkt.PeerAddr.String())
	}
	if pkt.IAID != 0 {
		parts = append(parts, fmt.Sprintf("%d", pkt.IAID))
	}
	if len(parts) == 0 {
		err := errors.New("slaac seed is empty")
		slog.Warn("dhcpv6 slaac seed build failed",
			slog.Bool("has_duid", pkt.DUID != ""),
			slog.Bool("has_client_mac", pkt.ClientMAC != nil),
			slog.Bool("has_link_addr", pkt.LinkAddr != nil),
			slog.Bool("has_peer_addr", pkt.PeerAddr != nil),
			slog.Uint64("iaid", uint64(pkt.IAID)),
			slog.String("error", err.Error()),
		)
		return "", err
	}
	return strings.Join(parts, "|"), nil
}

// deriveSLAACAddress deterministically derives a SLAAC IPv6 address from prefix and seed.
//
// Parameters:
//   - prefix: IPv6 subnet prefix used as network bits.
//   - seed: deterministic identity seed generated by buildSLAACSeed.
//
// Returns:
//   - netip.Addr: derived IPv6 address when successful.
//   - error: non-nil for invalid prefix/seed, conversion failures, or SLAAC rule violations.
//
// Applicable scenario:
//   - Used to generate stable host addresses in DHCPv6 environments that also deliver SLAAC hints.
func deriveSLAACAddress(prefix netip.Prefix, seed string) (netip.Addr, error) {
	if !prefix.IsValid() || !prefix.Addr().Is6() {
		err := fmt.Errorf("invalid IPv6 prefix: %q", prefix.String())
		slog.Warn("dhcpv6 slaac derive failed",
			slog.String("prefix", prefix.String()),
			slog.String("error", err.Error()),
		)
		return netip.Addr{}, err
	}
	if seed == "" {
		err := errors.New("slaac seed is empty")
		slog.Warn("dhcpv6 slaac derive failed",
			slog.String("prefix", prefix.String()),
			slog.String("error", err.Error()),
		)
		return netip.Addr{}, err
	}
	hostBits := 128 - prefix.Bits()
	if hostBits <= 0 {
		err := fmt.Errorf("invalid prefix bits for slaac host derivation: %d", prefix.Bits())
		slog.Warn("dhcpv6 slaac derive failed",
			slog.String("prefix", prefix.String()),
			slog.Int("prefix_bits", prefix.Bits()),
			slog.String("error", err.Error()),
		)
		return netip.Addr{}, err
	}
	sum := seedHash(seed)
	hostBigInt := borrowBigInt()
	defer releaseBigInt(hostBigInt)
	hostBigInt.SetBytes(sum[:])

	maxHosts := borrowBigInt()
	defer releaseBigInt(maxHosts)
	maxHosts.Lsh(big.NewInt(1), uint(hostBits))
	if maxHosts.Sign() <= 0 {
		err := errors.New("invalid host space for slaac derivation")
		slog.Error("dhcpv6 slaac big.Int host space failed",
			slog.String("prefix", prefix.String()),
			slog.Int("host_bits", hostBits),
			slog.String("error", err.Error()),
		)
		return netip.Addr{}, err
	}
	hostBigInt.Mod(hostBigInt, maxHosts)
	networkAddr := netutil.AddrToBig(prefix.Masked().Addr())
	if networkAddr == nil {
		err := errors.New("failed converting network prefix to big.Int")
		slog.Error("dhcpv6 slaac network conversion failed",
			slog.String("prefix", prefix.String()),
			slog.String("error", err.Error()),
		)
		return netip.Addr{}, err
	}
	network := borrowBigInt()
	defer releaseBigInt(network)
	network.Set(networkAddr)

	candidate := borrowBigInt()
	defer releaseBigInt(candidate)
	candidate.Add(network, hostBigInt)
	addr, ok := netutil.BigToAddr(candidate)
	if !ok {
		err := errors.New("failed converting big.Int candidate to IPv6 address")
		slog.Error("dhcpv6 slaac address conversion failed",
			slog.String("prefix", prefix.String()),
			slog.String("candidate", candidate.String()),
			slog.String("error", err.Error()),
		)
		return netip.Addr{}, err
	}
	if !IsValidSLAACAddr(addr, prefix) {
		err := errors.New("generated address does not satisfy SLAAC constraints")
		slog.Warn("dhcpv6 slaac derived address rejected",
			slog.String("prefix", prefix.String()),
			slog.String("address", addr.String()),
			slog.String("error", err.Error()),
		)
		return netip.Addr{}, err
	}
	return addr, nil
}

// IsValidSLAACAddr validates whether an IPv6 address is acceptable for SLAAC use.
// RFC 4862 Section 5.5.3 excludes reserved interface identifiers such as all-zero
// (Subnet-Router anycast) and, in this implementation, all-ones host IDs are also rejected.
// RFC 4862 Section 5.3 requires link-local configuration; when a link-local prefix
// (fe80::/10) is used, this function enforces canonical link-local address form.
//
// Parameters:
//   - addr: candidate IPv6 address to validate.
//   - prefix: subnet prefix that addr must belong to.
//
// Returns:
//   - bool: true when the address satisfies SLAAC constraints for this prefix.
//
// Applicable scenario:
//   - Used as final validation before emitting SLAAC hint address to clients.
func IsValidSLAACAddr(addr netip.Addr, prefix netip.Prefix) bool {
	if !addr.IsValid() || !addr.Is6() || !prefix.IsValid() || !prefix.Addr().Is6() {
		return false
	}
	maskedPrefix := prefix.Masked()
	if !maskedPrefix.Contains(addr) {
		return false
	}
	hostBits := 128 - maskedPrefix.Bits()
	if hostBits <= 0 {
		return false
	}
	network := netutil.AddrToBig(maskedPrefix.Addr())
	address := netutil.AddrToBig(addr)
	if network == nil || address == nil {
		return false
	}
	hostBigInt := new(big.Int).Sub(address, network)
	if hostBigInt.Sign() < 0 {
		return false
	}
	maxHosts := new(big.Int).Lsh(big.NewInt(1), uint(hostBits))
	if hostBigInt.Cmp(maxHosts) >= 0 {
		return false
	}
	if hostBigInt.Sign() == 0 {
		return false
	}
	hostAllOnes := new(big.Int).Sub(maxHosts, big.NewInt(1))
	if hostBigInt.Cmp(hostAllOnes) == 0 {
		return false
	}
	if maskedPrefix.Bits() == 10 && maskedPrefix.Addr() == linkLocal10Prefix.Addr() {
		if !addr.IsLinkLocalUnicast() {
			return false
		}
		if !linkLocal64Prefix.Contains(addr) {
			return false
		}
	}
	return true
}
